
version: "3.8"
services:
  app:
    build: .
    container_name: myapp_dev
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    environment:
      - NODE_ENV=development
    env_file:
      - .env.dev
